---

- name: Download 'influxdb-stats-exporter' 
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/

- name: Giving permission and upload influx_stats_exporter_linux_amd64 
  file:
    path: /usr/local/bin/influx_stats_exporter_linux_amd64
    owner: root
    group: root
    mode: 0755

- name: make a service unit
  template:
    src: prometheus-influxdb-stats-exporter.service.j2
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
    owner: prometheus
    group: prometheus
  no_log: true
  notify:
    - Reload daemons
    - Restart prometheus-influxdb-stats-exporter
    
- name: Execute handlers
  meta: flush_handlers

- name: Ensure influxdb-stats-exporter is started
  service:
    name: prometheus-influxdb-stats-exporter
    state: started
    enabled: yes

