---


- name: Add grafana gpg key
  apt_key: 
    url: https://packages.grafana.com/gpg.key
  
- name: Add grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install 'grafana'
  apt: 
    name: grafana

- name: reconfigure grafana by copying grafana.ini.j2 to grafana.ini
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: 
    - Restart grafana
 
  no_log: true

- name: Start grafana
  service:
    name: grafana-server
    state: started
    enabled: yes



- name: Copy datasource.yaml to /etc/grafana/provisioning/datasources/
  template:
    src: datasource.yaml
    dest: /etc/grafana/provisioning/datasources/datasource.yaml
  notify: Restart grafana


- name: Copy dashboard.yaml to /etc/grafana/provisioning/dashboards/
  template:
    src: dashboard.yaml
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart grafana

- name: Create directory for dashboard?
  file:
    path: /var/lib/grafana/dashboards
    state: directory
    mode: 0755

- name: Copy main.json to /var/lib/grafana/dashboards
  copy:
    src: main.json
    dest: /var/lib/grafana/dashboards/main.json
  notify: Restart grafana


- name: Copy latency.json to /var/lib/grafana/dashboards
  copy:
    src: latency.json
    dest: /var/lib/grafana/dashboards/latency.json
  notify: Restart grafana


- name: Copy syslog.json to /var/lib/grafana/dashboards
  copy:
    src: syslog.json
    dest: /var/lib/grafana/dashboards/syslog.json
  notify: Restart grafana


- name: Copy mysql.json to /var/lib/grafana/dashboards
  copy:
    src: mysql.json
    dest: /var/lib/grafana/dashboards/mysql.json
  notify: Restart grafana

  