---

- name: Install 'iptables-persistent'
  apt:
    name:
      - iptables-persistent
    state: present

- name: fix ssl handshake docker
  template:
    src: iptables.mangle.j2
    dest: /etc/iptables/rules.v4    

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Ensure netfilter-persistent is started
  service:
    name: netfilter-persistent
    state: started
    enabled: yes

- name: Load iptable-mangle config
  community.general.iptables_state:
    state: restored    
    path: /etc/iptables/rules.v4      
    table: mangle

    