{
 "title": "main",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  { "title": "CPU & RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_build_info" }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grafana_build_info" }
   ]
  },
  {
   "title": "CPU Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "RAM Active Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_memory_Active_bytes[1m])"
    }
   ]
  },
  { "title": "NGINX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Nginx Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "Nginx HTTP Requests Per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  { "title": "MYSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "MySQL Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "MySQL Commands Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total[1m])"
    }
   ]
  },
  { "title": "BIND9", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Bind9 Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "DNS Total Queries Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])"
    }
   ]
  },
  { "title": "INFLUXDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Influxdb Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success"
    }
   ]
  },
  {
   "title": "Influxdb Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])"
    }
   ]
  },
  { "title": "EXPORTERS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Node Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_exporter_build_info" }
   ]
  },
  {
   "title": "Bind Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_exporter_build_info" }
   ]
  },
  {
   "title": "Nginx Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginxexporter_build_info" }
   ]
  },
  {
   "title": "Influxdb Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_stats_exporter_build_info"
    }
   ]
  },
  {
   "title": "MySQL Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysqld_exporter_build_info" }
   ]
  },
  {
   "title": "HAProxy Exporter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_exporter_build_info" }
   ]
  },
  { "title": "HAPROXY & KEEPALIVED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Keepalived Master Slave Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state" }
   ]
  },
  {
   "title": "Keepalived Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_up" }
   ]
  },
  {
   "title": "HAProxy Frontend Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "HAProxy Backend Health",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "haproxy_server_up" }
   ]
  }
 ]
}