---


- name: Add the user 'agama'
  user:
    name: "{{ agama_user }}"
    system: yes
    state: present

- name: Create install directory /opt/agama
  file:
    state: directory
    path: /opt/agama
    owner: agama
    mode: 0755

- name: Install 'python3-flask-sqlalchemy'
  apt: 
    name: python3-flask-sqlalchemy

- name: Install 'python3-pymysql'
  apt: 
    name: python3-pymysql 

- name: Download 'agama.py'
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
    mode: 0644

    