---

- name: Create the backup directory for influxdb
  file:
    path: /home/backup/influxdb
    state: directory
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: 0700

- name: Copy influxdb-backup.j2 to /etc/cron.d/influxdb-backup  (Upload influxdb cron)
  template:
    src: influxdb-backup.j2
    dest: /etc/cron.d/influxdb-backup
    owner: root
    group: root
    mode: 0644
  tags: cron

- name: Ensure Cron is started
  service:
    name: cron
    state: started
    enabled: yes
  tags: cron
