---
apiVersion: 1

datasources:
 - name: prometheus
   type: prometheus

   url: http://prometheus:/prometheus
   password:
   user:
   database:
   isDefault: true
   editable: true

 - name: InfluxDB
   type: influxdb

   url: http://influxdb:8086
   password:
   user:
   database: latency
   editable: true

 - name: InfluxDB-telegraf
   type: influxdb

   url: http://influxdb:8086
   password:
   user:
   database: telegraf
   editable: true

