---

- name: Install 'keepalived'
  apt:
    name:
      - keepalived

- name: Add user keepalived_script
  user:
    name: "keepalived_script"
    home: /home/keepalived_script


- name: Copy vrrp_script.j2 to /home/keepalived_script/vrrp_script
  template:
    src: vrrp_script.j2
    dest: /home/keepalived_script/vrrp_script
  notify: Restart keepalived

- name: Copy keepalived.conf to /etc/keepalived/keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

- name: Copy ha88.j2 to /usr/local/bin/ha88
  template:
    src: ha88.j2
    dest: /usr/local/bin/ha88
    owner: keepalived_script
    group: keepalived_script
    mode: 0755
  notify: 
    - Restart keepalived
   
- name: Ensure keepalived is started
  service:
    name: keepalived
    state: started

