---

- name: Download keepalived exporter 
  unarchive:
    src: https://github.com/cafebazaar/keepalived-exporter/releases/download/v1.2.0/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name:  create keepalived prometheus exporter service
  template:
    src: keepalived-prometheus-exporter.service.j2
    dest: /etc/systemd/system/keepalived-prometheus-exporter.service
  notify:
    - Reload daemons
    - Restart keepalived_exporter

- name: Execute handlers
  meta: flush_handlers

- name: Ensure that keepalived exporter is started
  service:
    name: keepalived-prometheus-exporter.service
    state: started
    enabled: yes

    