---

- name: rndc reload
  ansible.builtin.shell: rndc reload

- name: Restart haproxy
  service:
    name: haproxy
    state: restarted

- name: Restart haproxy-exporter
  service:
    name: prometheus-haproxy-exporter
    state: restarted

