
---

- name: Install 'prometheus'
  apt:
    name: prometheus

- name: Copy prometheus.yml.j2 to /etc/prometheus/prometheus.yml / prometheus config
  template:
   src: prometheus_apt.yml.j2
   dest: /etc/prometheus/prometheus.yml
  notify: Restart prometheus

- name: Copy prometheus.j2 to /etc/default/prometheus / reverse proxy config
  template:
   src: prometheus.j2
   dest: /etc/default/prometheus
  notify: Restart prometheus

- name: Ensure prometheus is running
  service:
    name: prometheus
    state: started
    enabled: yes

    